version: "3"
services:
  klipper-ubuntu:
    container_name: klipper-ubuntu
    build:
      context: .
    command: /sbin/init
    privileged: true
    ports:
      - 80:80
      - 7125:7125
      - 2222:22
    tty: true
    #user: "1000:1000"